### ISSUE TITLE
certainly not the best interaction handler or, yeah not something i would suggest

### ISSUE THREAD

**Issue by sm0lvoicc** [kabirsingh2004/Discord-V14-Handler#1]
your event handler has a few things to be made better
> the way you are dealing with the interactions won't be the best for the buttons since you are first checking if the `INTERACTION_CREATE` event gives you a component type or not, i would suggest you to first check for the event having components and then check for the slash commands because you are using a require cache type handler which would fail the interactions when you add many commands

> you are deffering the interaction response from the event handler which is TOTALLY NOT THE BEST THING TO DO, i would suggest you to defer the interaction from the command files and then do stuff

> once go through https://discord.dev/ you are replying with a `followUp` to a deferred interaction which works well for now, but further more i would suggest you to use `editReply` because, i  mean, the name `followUp` tells that it is for a followed up reply to an interaction, when you are just sending a `TYPE 5` not a `TYPE 4`, 

> the way you are handling the interaction.defer() error, thats wrong, you are not alerting the user that there has been an error internally in the code, so yeah send a ephemeral (flags 64) type 4 reply saying that there was an error hence the command won't be ran further more

**Comment by kabirjaipal** [comment]
ok i make better
Thanks for Suggest

**Comment by sm0lvoicc** [comment]
yes also close the issue once you are done
